---
# tasks file for tomcat
 - name: Downloading required tomcat
   get_url:
    url: "{{tomcat_url}}"
    dest: /usr/local
 - name: Extracting downloaded tomcat
   unarchive:
    src: "/usr/local/apache-tomcat-{{req_tomcat_ver}}.tar.gz"
    dest: /usr/local
    remote_src: yes
 - name: Renaming tocmcat home
   command: mv /usr/local/apache-tomcat-{{req_tomcat_ver}} /usr/local/latest
   run_once: true
   ignore_errors: true
 - name: Replacing default port with required port
   template:
    src: templates/server.xml.j2
    dest: /usr/local/latest/conf/server.xml
   notify: start_tomcat 
